# Generated by Django 3.1.5 on 2021-03-26 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
        ),
    ]
