# Generated by Django 3.1.5 on 2021-03-26 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
