# Generated by Django 3.1.5 on 2021-03-26 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_auto_20210326_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
