# Generated by Django 3.1.5 on 2021-03-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20210326_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_points',
            field=models.IntegerField(default=0),
        ),
    ]
