# Generated by Django 3.1.5 on 2021-03-26 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_auto_20210326_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_pub_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
