# Generated by Django 3.1.5 on 2021-04-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20210326_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_pub_date',
            field=models.DateTimeField(),
        ),
    ]
