# Generated by Django 3.2 on 2021-04-20 10:58

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20210326_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_pub_date',
            field=models.DateTimeField(),
        ),
    ]
