# Generated by Django 3.1.5 on 2021-04-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0009_auto_20210420_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_pub_date',
            field=models.DateField(),
        ),
    ]
