# Generated by Django 3.2 on 2021-04-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0009_auto_20210420_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_calories',
            field=models.IntegerField(default=0),
        ),
    ]
