# Generated by Django 3.1.5 on 2021-04-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_auto_20210420_0406'),
        ('exercise', '0009_auto_20210420_1058'),
    ]

    operations = [
    ]
