# Generated by Django 3.1.5 on 2021-04-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_merge_20210420_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='workout_calories',
        ),
    ]
