# Generated by Django 3.1.5 on 2021-04-20 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0012_remove_workout_workout_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_pub_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
